#----------Imports----------#

import pymel.core as pm
import pRigging.src.riggingbase as prb

#----------ArmTabNovice-Class----------#

class ArmTabNovice(prb.RiggingBase):
    
    """
        Class: ArmTabNovice
            A class containing all of the code for generating an arm tab 
            for the novice dificulty rating 
        
        File: pRigging/src/ui/armtabnovice.py
        
        Contains:
            self.m_topLayout

        Imports:
            pymel.core as pm
            pRigging.src.riggingbase as prb     
    """
    
    def __init__(self,_parent,_guiInstance,_name, _arm):
        
        """
            Method: __init__
                A method called when the class is instanciated, sets up the attributes
            
            Inputs:
                self:                   A pointer to the instance of the object being
                                        created.
                _parent:                The parent ui element for the layout
                _guiInstance:           The instance of the GUI class
                _name:                  The name to attempt to call the tab, a unique
                                        name will be generated if the one passed in cannot be used
                _arm:                   The rig Component passed in by the ui 
        """
        
        #set the parent ui 
        
        pm.setParent(_parent)
        
        #and store a pointer to the gui instance for calling parent methods to add a tab 
        
        self.m_gui = _guiInstance
        
        #check if the name exists, if it does, add a number to make it unique
        
        result = False
        
        #store the name
        
        self.m_name = _name
             
        i = 1
                
        while not result:
                
            if pm.formLayout(self.m_name, q = True, ex = True):
            
                self.m_name = self.addExtToNames(self.removeExtFromNames([self.m_name]), str(i))[0]
                
            else:
                
                result = True
                    
            i = i+1
        
        #set the layout
        
        self.m_topLayout =  pm.formLayout(self.m_name, numberOfDivisions = 100)
        
        #set up the rig component
        
        self.m_arm = _arm
        
        #add text
        
        #-------------step 1 text generate-------------#
        
        self.m_step1Label = pm.text(label="Step 1:", fn = "boldLabelFont")
        self.m_step1Text = pm.text(label = "Build the template joint chain for your arm", 
                                    ann = "At this point, I can't really help, you need to at least know where you want the joints",
                                    al = "left",
                                    fn = "smallBoldLabelFont",
                                    ww = True)
                                    
        self.m_note1Text = pm.text(label = "Note: There is no need to build twist joints, these will be generated by the tool if you set that option", 
                                    al = "left",
                                    h = 20,
                                    fn = "smallPlainLabelFont",
                                    ww = True)
        
        #-------------step 1 control generate-------------#
        
        self.m_jointToolButton = pm.button(l = "Joint Tool")
        
        #-------------step 2 text generate-------------#
        
        self.m_step2Label = pm.text(label="Step 2:", fn = "boldLabelFont")
        self.m_step2Text = pm.text(label = "Select the joints and load them into the box below", 
                                    ann = "The joints must be in an unbroken and single hirerarchy\n there must not be more than one child of any selected\n joint also selected",
                                    al = "left",
                                    fn = "smallBoldLabelFont",
                                    h = 20,
                                    ww = True)
        
        #-------------step 3 text generate-------------#
                
        self.m_step3Label = pm.text(label="Step 3:", fn = "boldLabelFont")
        self.m_step3Text = pm.text(label = "Select the options and Generate", 
                                    al = "left",
                                    fn = "smallBoldLabelFont",
                                    h = 20,
                                    ww = True)
                                    
        #-------------step 2 control generate-------------#
        
        self.m_jointTable = pm.textScrollList()
        self.m_loadJointsButton = pm.button(l = "Load Joints")
        
        #-------------step 3 control generate-------------#
        
        self.m_ikCheck = pm.checkBox(l = "IK", ann = "Generate an IK chain?", v = True)
        self.m_fkCheck = pm.checkBox(l = "FK", ann = "Generate an FK chain?", v = True)
        self.m_twistCheck = pm.checkBox(l = "Forearm Twist", ann = "Add a forearm twist chain?", v = True)        
        
        self.m_genRigButton = pm.button(l = "Generate Rig")
        
        #-------------misc control generate-------------#
        
        self.m_closeButton = pm.button(l = "Close Tab")
        

        #-------------step 1 text attach-------------#
        
        self.m_topLayout.attachForm(self.m_step1Label, 'left', 20)
        self.m_topLayout.attachForm(self.m_step1Text, 'right', 20)
        self.m_topLayout.attachForm(self.m_step1Label, 'top', 20)
        self.m_topLayout.attachForm(self.m_step1Text,'top', 20)
        
        self.m_topLayout.attachControl(self.m_step1Text,'left', 20, self.m_step1Label)
        
        self.m_topLayout.attachForm(self.m_note1Text, 'left', 30)
        self.m_topLayout.attachForm(self.m_note1Text, 'right', 20)
        
        self.m_topLayout.attachControl(self.m_note1Text, 'top', 10, self.m_step1Text)
        
        self.m_topLayout.attachPosition(self.m_note1Text, 'bottom', 5, 20)
        
        #-------------step 1 controls attach-------------#
        
        self.m_topLayout.attachForm(self.m_jointToolButton, 'left', 30)
        self.m_topLayout.attachForm(self.m_jointToolButton, 'right', 20)
        
        self.m_topLayout.attachControl(self.m_jointToolButton, 'top', 20, self.m_note1Text)
        
        #-------------step 2 text attach-------------#
        
        self.m_topLayout.attachForm(self.m_step2Label, 'left', 20)       
        self.m_topLayout.attachControl(self.m_step2Label, 'top', 20, self.m_jointToolButton)

        self.m_topLayout.attachPosition(self.m_step2Text, 'right', 5, 50)       
        self.m_topLayout.attachControl(self.m_step2Text, 'top', 17, self.m_jointToolButton)
        self.m_topLayout.attachControl(self.m_step2Text, 'left', 20, self.m_step2Label)
        
        #-------------step 3 text attach-------------#
        
        self.m_topLayout.attachPosition(self.m_step3Label, 'left', 20,50)       
        self.m_topLayout.attachControl(self.m_step3Label, 'top', 20, self.m_jointToolButton)

        self.m_topLayout.attachForm(self.m_step3Text, 'right', 20)       
        self.m_topLayout.attachControl(self.m_step3Text, 'top', 17, self.m_jointToolButton)
        self.m_topLayout.attachControl(self.m_step3Text, 'left', 20, self.m_step3Label)
        
        
        #-------------step 2 control attach-------------#
        
        self.m_topLayout.attachForm(self.m_jointTable, 'left', 30)
        self.m_topLayout.attachPosition(self.m_jointTable, 'right', 20, 50)
        self.m_topLayout.attachControl(self.m_jointTable,'top', 20, self.m_step2Text)
        self.m_topLayout.attachControl(self.m_jointTable,'bottom', 20, self.m_loadJointsButton)
                
        self.m_topLayout.attachForm(self.m_loadJointsButton, 'left', 20)
        self.m_topLayout.attachControl(self.m_loadJointsButton, 'right', 20, self.m_genRigButton)
        self.m_topLayout.attachControl(self.m_loadJointsButton, 'bottom', 20,self.m_closeButton)
        
        #-------------step 3 control attach-------------#
        
        self.m_topLayout.attachForm(self.m_ikCheck, 'right',20)
        self.m_topLayout.attachForm(self.m_fkCheck, 'right',20)
        self.m_topLayout.attachForm(self.m_twistCheck, 'right',20)
        
        self.m_topLayout.attachPosition(self.m_ikCheck, 'left' , 40 , 50)
        self.m_topLayout.attachPosition(self.m_fkCheck, 'left' , 40 , 50)
        self.m_topLayout.attachPosition(self.m_twistCheck, 'left' , 40 , 50)
        
        self.m_topLayout.attachControl(self.m_ikCheck, 'top', 10, self.m_step3Text)
        self.m_topLayout.attachControl(self.m_fkCheck, 'top', 10, self.m_ikCheck)
        self.m_topLayout.attachControl(self.m_twistCheck, 'top', 10, self.m_fkCheck)
        
        self.m_topLayout.attachForm(self.m_genRigButton, 'right', 20)
        self.m_topLayout.attachPosition(self.m_genRigButton, 'left', 20, 50)
        self.m_topLayout.attachControl(self.m_genRigButton, 'bottom', 20,self.m_closeButton)
                
        #-------------misc control attach-------------#
                
        self.m_topLayout.attachForm(self.m_closeButton, 'left', 20)
        self.m_topLayout.attachForm(self.m_closeButton, 'right', 20)
        self.m_topLayout.attachForm(self.m_closeButton, 'bottom', 20)
        
        
                                     

#----------END-ArmTabNovice-Class----------#       