#----------Imports----------#

import pymel.core as pm
import pRigging.src.riggingbase as prb

#----------ArmTabNovice-Class----------#

class ArmTabNovice(prb.RiggingBase):
    
    """
        Class: ArmTabNovice
            A class containing all of the code for generating an arm tab 
            for the novice dificulty rating 
        
        File: pRigging/src/ui/armtabnovice.py
        
        Contains:
            self.m_topLayout

        Imports:
            pymel.core as pm
            pRigging.src.riggingbase as prb     
    """
    
    def __init__(self,_parent,_guiInstance,_name, _arm):
        
        """
            Method: __init__
                A method called when the class is instanciated, sets up the attributes
            
            Inputs:
                self:                   A pointer to the instance of the object being
                                        created.
                _parent:                The parent ui element for the layout
                _guiInstance:           The instance of the GUI class
                _name:                  The name to attempt to call the tab, a unique
                                        name will be generated if the one passed in cannot be used
                _arm:                   The rig Component passed in by the ui 
        """
        
        #set the parent ui 
        
        pm.setParent(_parent)
        
        #and store a pointer to the gui instance for calling parent methods to add a tab 
        
        self.m_gui = _guiInstance
        
        #check if the name exists, if it does, add a number to make it unique
        
        result = False
        
        #store the name
        
        self.m_name = _name
             
        i = 1
                
        while not result:
                
            if pm.formLayout(self.m_name, q = True, ex = True):
            
                self.m_name = self.addExtToNames(self.removeExtFromNames([self.m_name]), str(i))[0]
                
            else:
                
                result = True
                    
            i = i+1
        
        #set the layout
        
        self.m_topLayout =  pm.formLayout(self.m_name, numberOfDivisions = 100)
        
        #set up the rig component
        
        self.m_arm = _arm
        
        #add text
        
        self.m_step1Label = pm.text(label="Step 1:", fn = "boldLabelFont")
        self.m_step1Text = pm.text(label = "Build the template joint chain for your arm", 
                                    ann = "At this point, I can't really help, you need to at least know where you want the joints",
                                    al = "left",
                                    fn = "smallBoldLabelFont",
                                    ww = True)
                                    
        self.m_note1Text = pm.text(label = "Note: There is no need to build twist joints, these will be generated by the tool if you set that option", 
                                    al = "left",
                                    h = 20,
                                    fn = "smallPlainLabelFont",
                                    ww = True)
        
        self.m_jointToolButton = pm.button(l = "Joint Tool")
        
        self.m_step2Label = pm.text(label="Step 2:", fn = "boldLabelFont")
        self.m_step2Text = pm.text(label = "Select the joints and load them into the box below", 
                                    ann = "The joints must be in an unbroken and single hirerarchy\n there must not be more than one child of any selected\n joint also selected",
                                    al = "left",
                                    fn = "smallBoldLabelFont",
                                    h = 20,
                                    ww = True)
                                    
        self.m_step3Label = pm.text(label="Step 3:", fn = "boldLabelFont")
        self.m_step3Text = pm.text(label = "Select the options and Generate", 
                                    al = "left",
                                    fn = "smallBoldLabelFont",
                                    h = 20,
                                    ww = True)
        
        self.m_loadJointsButton = pm.button(l = "Load Joints")
        
        self.m_genJointsButton = pm.button(l = "Generate Joints")
        
        self.m_closeButton = pm.button(l = "Close Tab")
        
        #attach the first text to the form
        
        self.m_topLayout.attachForm(self.m_step1Label, 'left', 20)
        self.m_topLayout.attachForm(self.m_step1Text, 'right', 20)
        self.m_topLayout.attachForm(self.m_step1Label, 'top', 20)
        self.m_topLayout.attachForm(self.m_step1Text,'top', 20)
        
        self.m_topLayout.attachControl(self.m_step1Text,'left', 20, self.m_step1Label)
        
        self.m_topLayout.attachForm(self.m_note1Text, 'left', 30)
        self.m_topLayout.attachForm(self.m_note1Text, 'right', 20)
        
        self.m_topLayout.attachControl(self.m_note1Text, 'top', 10, self.m_step1Text)
        
        self.m_topLayout.attachPosition(self.m_note1Text, 'bottom', 5, 20)
        
        self.m_topLayout.attachForm(self.m_jointToolButton, 'left', 30)
        self.m_topLayout.attachForm(self.m_jointToolButton, 'right', 20)
        
        self.m_topLayout.attachControl(self.m_jointToolButton, 'top', 20, self.m_note1Text)
        
        self.m_topLayout.attachForm(self.m_step2Label, 'left', 20)       
        self.m_topLayout.attachControl(self.m_step2Label, 'top', 20, self.m_jointToolButton)

        self.m_topLayout.attachPosition(self.m_step2Text, 'right', 5, 50)       
        self.m_topLayout.attachControl(self.m_step2Text, 'top', 20, self.m_jointToolButton)
        self.m_topLayout.attachControl(self.m_step2Text, 'left', 20, self.m_step2Label)
        
        self.m_topLayout.attachPosition(self.m_step3Label, 'left', 10,50)       
        self.m_topLayout.attachControl(self.m_step3Label, 'top', 20, self.m_jointToolButton)

        self.m_topLayout.attachForm(self.m_step3Text, 'right', 20)       
        self.m_topLayout.attachControl(self.m_step3Text, 'top', 20, self.m_jointToolButton)
        self.m_topLayout.attachControl(self.m_step3Text, 'left', 20, self.m_step3Label)
        
        self.m_topLayout.attachForm(self.m_loadJointsButton, 'left', 20)
        self.m_topLayout.attachControl(self.m_loadJointsButton, 'right', 10, self.m_genJointsButton)
        self.m_topLayout.attachControl(self.m_loadJointsButton, 'bottom', 20,self.m_closeButton)
        
        self.m_topLayout.attachForm(self.m_genJointsButton, 'right', 20)
        self.m_topLayout.attachPosition(self.m_genJointsButton, 'left', 10, 50)
        self.m_topLayout.attachControl(self.m_genJointsButton, 'bottom', 20,self.m_closeButton)
                
        self.m_topLayout.attachForm(self.m_closeButton, 'left', 20)
        self.m_topLayout.attachForm(self.m_closeButton, 'right', 20)
        self.m_topLayout.attachForm(self.m_closeButton, 'bottom', 20)
        
        
                                     

#----------END-ArmTabNovice-Class----------#       